name: Publish

on: 
  workflow_dispatch:
  push:
    branches:
    - Master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore -r linux-x64 ./Backend/MinimalApiCQRS.sln 

      - name: Build
        run: dotnet build ./Backend/MinimalApiCQRS.sln  --configuration Release --no-restore

      - name: Test
        run: dotnet test ./Backend/MinimalApiCQRS.sln --configuration Release --no-restore --no-build --verbosity normal

      - name: Publish
        run: dotnet publish -r linux-x64 --no-self-contained ./Backend/MinimalApiCQRS.sln  --configuration Release
